feat: Search panel
SoftwareEngineeringRegisterPlatform/AndroidFrontEnd pull request #15
Opened 2021-06-20 18:39 UTC by diaozhongpu

only goto hospital page

2021-06-20 19:02 UTC, diaozhongpu commented
hotfix for line111, 125@app/src/main/java/cn/hospital/registerplatform/data/dto/HospitalInfo.kt from #16

2021-06-20 19:42 UTC, diaozhongpu commented
![image](https://user-images.githubusercontent.com/48541039/122686195-8ff7fa80-d242-11eb-93e3-c6fcad102899.png)
![image](https://user-images.githubusercontent.com/48541039/122686214-971f0880-d242-11eb-87f9-263f1abbf66d.png)
![image](https://user-images.githubusercontent.com/48541039/122686227-9edead00-d242-11eb-93a9-a2ab69e8f0d1.png)
![image](https://user-images.githubusercontent.com/48541039/122686237-a69e5180-d242-11eb-95e0-f7d7a5a4f70d.png)

2021-06-21 01:09 UTC, Borealin requested changes

2021-06-21 01:09 UTC, Borealin commented on app/src/main/java/cn/hospital/registerplatform/data/repository/HospitalRepository.kt
> +            hospitalApi.getHospitalFilterList(Gson().toJson(mapOf("name" to name)), loadType, page, size)
No need to use gson

2021-06-21 01:09 UTC, Borealin commented on app/src/main/java/cn/hospital/registerplatform/ui/component/hospital/HospitalListActivity.kt
> +            hospitalSearchName.afterTextChanged { text ->
could use data binding's bidirectional binding

2021-06-21 01:09 UTC, Borealin commented on app/src/main/java/cn/hospital/registerplatform/ui/component/main/HomeFragment.kt
> +                    startActivity(HospitalListActivity.newIntent(view.context))
maybe use requireContext instead of view.context

2021-06-21 11:38 UTC, Borealin approved these changes

2021-06-21 11:38 UTC, merged